name: Rafael Dev 21, O Rayquaza Bolad√£o
markdown: kramdown

disqus:
  shortname: rafaeldev21
  
url: "https://rafael-dev-21.netlify.app"

plugins:
  - jekyll-feed
  - jekyll-netlify
  
collections:
  jogos:
    - output: true
    - description: true
    - title: true
    - cover: true
    - jogo_url: true
    - width: true
    - height: true

permalink: /blog/:year/:month/:day/:title
